# Generated by Django 3.2.3 on 2021-05-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20210516_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='تعداد'),
        ),
    ]
