# Generated by Django 3.2.3 on 2021-05-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_cart_subtotal'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='carts_cart_user_id_f43479_idx'),
        ),
    ]
