# Generated by Django 3.2.3 on 2021-05-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cart_carts_cart_user_id_f43479_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_pay',
            field=models.BooleanField(default=False, verbose_name='آیا پرداخت شده'),
        ),
    ]
