# Generated by Django 2.2.23 on 2021-07-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20210622_1609'),
        ('carts', '0006_auto_20210602_1702'),
        ('carts', '0005_auto_20210624_1447'),
    ]

    operations = [
    ]
