# Generated by Django 3.2.3 on 2021-05-14 20:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, verbose_name='موضوع')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_product', models.JSONField(verbose_name='فیلد های این دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='تایتل')),
                ('slug', models.SlugField(blank=True, verbose_name='عنوان')),
                ('description', models.JSONField(verbose_name='مشخصات محصول')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ساخته ')),
                ('category', models.ManyToManyField(to='products_app.Category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله ها',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='form_field',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='products_app.formfield', verbose_name='فیلدها'),
        ),
    ]
