# Generated by Django 3.2.3 on 2021-05-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
