# Generated by Django 3.2.3 on 2021-05-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_ap_slug_e95fc7_idx'),
        ),
    ]
