# Generated by Django 3.2.3 on 2021-05-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_product_products_ap_slug_e95fc7_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='images',
            index=models.Index(fields=['product'], name='products_ap_product_815f4c_idx'),
        ),
    ]
