# Generated by Django 3.2.3 on 2021-05-15 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='form_field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products_app.formfield', verbose_name='فیلدها'),
        ),
    ]
