# Generated by Django 3.2.3 on 2021-05-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_delete_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='قیمت'),
        ),
    ]
