# Generated by Django 3.2.3 on 2021-05-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_images_products_ap_product_815f4c_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='products_ap_slug_f30445_idx'),
        ),
    ]
