# Generated by Django 3.2.3 on 2021-05-15 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_auto_20210515_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='category',
            name='form_field',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products_app.formfield', verbose_name='فیلدها'),
        ),
    ]
