# Generated by Django 3.2.3 on 2021-05-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_auto_20210515_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product', to='products_app.Category', verbose_name='دسته بندی'),
        ),
    ]
