# Generated by Django 3.2.3 on 2021-05-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟'),
        ),
    ]
