# Generated by Django 3.0.5 on 2021-05-29 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فروشنده'),
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Product', verbose_name='کدام محصول'),
        ),
        migrations.AddField(
            model_name='category',
            name='form_field',
            field=models.ManyToManyField(blank=True, default=None, to='items.FigureField', verbose_name='فیلدها'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.Category', verbose_name='زیردسته'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='items_produ_slug_f3279d_idx'),
        ),
        migrations.AddIndex(
            model_name='images',
            index=models.Index(fields=['product'], name='items_image_product_beecb8_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='items_categ_slug_1f2c47_idx'),
        ),
    ]
