# Generated by Django 2.2.23 on 2021-07-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20210622_1609'),
        ('items', '0004_auto_20210624_1447'),
        ('items', '0004_auto_20210602_1616'),
    ]

    operations = [
    ]
