# Generated by Django 2.2.23 on 2021-07-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_merge_20210714_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='عکس'),
        ),
    ]
