# Generated by Django 2.2.23 on 2021-07-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20210718_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/media/images/2.jpg', null=True, upload_to='images', verbose_name='عکس'),
        ),
    ]
