# Generated by Django 3.2.3 on 2021-05-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='choice',
            field=models.CharField(choices=[('d', 'درحال بررسی'), ('p', 'تغییرات صورت گرفته')], default='d', max_length=1, verbose_name='وضعیت'),
        ),
    ]
