# Generated by Django 3.2.3 on 2021-05-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='choice',
            field=models.CharField(choices=[('d', 'درحال بررسی'), ('p', 'تغییرات صورت گرفته')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
