# Generated by Django 3.2.3 on 2021-05-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_seller'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormField',
            new_name='FigureField',
        ),
    ]
