# Generated by Django 3.2.3 on 2021-05-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_formfield_figurefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='form_field',
        ),
        migrations.AddField(
            model_name='category',
            name='form_field',
            field=models.ManyToManyField(blank=True, null=True, to='products.FigureField', verbose_name='فیلدها'),
        ),
        migrations.AlterField(
            model_name='figurefield',
            name='type_product',
            field=models.CharField(max_length=200, verbose_name='فیلد های این دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='مشخصات محصول'),
        ),
    ]
